const campusCenter = '14.33571,78.53841';

// Prototype campus model. Outdoor navigation uses Google Maps; indoor navigation uses our rough layouts.
const blocks = [
  {name:'AB-1',icon:'🏢',query:'Academic Block 1, IIIT RGUKT RK Valley',type:'academic',smallDepartments:['Mathematics','Physics','Chemistry','English','Telugu','Management','Library Science','Physical Education']},
  {name:'AB-2',icon:'🏢',query:'Academic Block 2, IIIT RGUKT RK Valley',type:'academic',smallDepartments:['Mathematics','Physics','Chemistry','English','Telugu','Management','Library Science','Physical Education']},
  {name:'CSE Block',icon:'💻',query:'CSE Department, IIIT RGUKT RK Valley',type:'department',department:'Computer Science and Engineering'},
  {name:'ECE Block',icon:'📡',query:'ECE Department, IIIT RGUKT RK Valley',type:'department',department:'Electronics and Communication Engineering'},
  {name:'EEE Block',icon:'⚡',query:'EEE Department, IIIT RGUKT RK Valley',type:'department',department:'Electrical and Electronics Engineering'},
  {name:'Civil Block',icon:'🏗️',query:'Civil Engineering Department, IIIT RGUKT RK Valley',type:'department',department:'Civil Engineering'},
  {name:'MME Block',icon:'🔩',query:'MME Department, IIIT RGUKT RK Valley',type:'department',department:'Materials Science and Metallurgical Engineering'},
  {name:'ME Block',icon:'⚙️',query:'Mechanical Engineering Department, IIIT RGUKT RK Valley',type:'department',department:'Mechanical Engineering'},
  {name:'BH-1',icon:'🏠',query:'Boys Hostel 1, IIIT RGUKT RK Valley',type:'hostel'},
  {name:'BH-2',icon:'🏠',query:'Boys Hostel 2, IIIT RGUKT RK Valley',type:'hostel'},
  {name:'GH-1',icon:'🏠',query:'Girls Hostel 1, IIIT RGUKT RK Valley',type:'hostel'},
  {name:'SAC',icon:'🏟️',query:'Student Activity Centre, IIIT RGUKT RK Valley',type:'sports'},
  {name:'Campus Hospital',icon:'🏥',query:'Campus Hospital, IIIT RK Valley, Idupulapaya, Andhra Pradesh',type:'facility'},
  {name:'SBI Bank — Idupulapaya',icon:'🏦',query:'State Bank of India, Idupulapaya-Kadapa, AP IIIT Campus, RK Valley, Idupulapaya',type:'facility'},
  {name:'SBI ATM — IIIT Campus',icon:'🏧',query:'State Bank of India ATM, AP IIIT Campus, RK Valley, Idupulapaya',type:'facility'},
  {name:'Campus Temple',icon:'🛕',query:'Temple, IIIT RK Valley Campus, Idupulapaya, Andhra Pradesh',type:'temple'}
];

const academicFloors=[['101','102','103','104','105 — Mathematics','106 — Physics','107 — Chemistry','108 — English','109 — Telugu','110 — Academic Office'],['201','202','203','204','205 — Mathematics','206 — Physics','207 — Chemistry','208 — English','209 — Telugu','210 — Faculty / Staff Room'],['301','302','303','304','305 — Management','306 — Library Science','307 — Physical Education','308 — Faculty Room','309 — Seminar Room','310 — Common Area']];
const departmentFloors=[['101 — Department Office','102 — Faculty Room','103 — Classroom','104 — Classroom','105 — Classroom','106 — Classroom','107 — Classroom','108 — Student Room','109 — Meeting Room','110 — Common Area'],['201 — Classroom','202 — Classroom','203 — Classroom','204 — Classroom','205 — Teaching Lab','206 — Teaching Lab','207 — Project Lab','208 — Faculty Room','209 — Research Room','210 — Seminar Room'],['301 — Classroom','302 — Classroom','303 — Classroom','304 — Classroom','305 — Seminar Hall','306 — Project Lab','307 — Research Lab','308 — Faculty Room','309 — Meeting Room','310 — Student Activity Room']];
const hostelFloors=[['101','102','103','104','105','106','107','108','109','110 — Warden Office'],['201','202','203','204','205','206','207','208','209','210 — Common Room'],['301','302','303','304','305','306','307','308','309','310 — Study Room']];
const sacFloors=[['SAC Entrance','Gym','Indoor Gymnasium','Table Tennis','Badminton','Chess / Indoor Games','Student Clubs Room','Multipurpose Hall','Basketball Court','Tennis Court','Volleyball Court','Sports Office']];
const facilityFloors=[['Main Entrance','Reception / Help Desk','Main Facility Area','Waiting Area','Information Desk','Common Area']];
const templeFloors=[[]];
const floorNames=['Ground Floor','First Floor','Second Floor'];
const currentBuilding=document.getElementById('currentBuilding'),currentFloor=document.getElementById('currentFloor'),currentRoom=document.getElementById('currentRoom');
const destinationBuilding=document.getElementById('destinationBuilding'),destinationFloor=document.getElementById('destinationFloor'),destinationRoom=document.getElementById('destinationRoom');
const message=document.getElementById('message'),routeResult=document.getElementById('routeResult'),routeSummary=document.getElementById('routeSummary'),steps=document.getElementById('steps'),floorPreview=document.getElementById('floorPreview'),googleMaps=document.getElementById('googleMaps'),locations=document.getElementById('locations'),essentialLocations=document.getElementById('essentialLocations'),currentRoomField=document.getElementById('currentRoomField'),destinationRoomField=document.getElementById('destinationRoomField');
function floorsFor(b){if(blocks[b].type==='temple')return templeFloors;if(blocks[b].type==='hostel')return hostelFloors;if(blocks[b].type==='sports')return sacFloors;if(blocks[b].type==='facility')return facilityFloors;if(blocks[b].type==='department')return departmentFloors;return academicFloors;}
function roomsFor(b,f){return floorsFor(b)[f]||[];}
function floorLabel(b,f){if(blocks[b].type==='temple')return 'Ground Floor';if(blocks[b].type==='sports')return 'SAC / Ground Level';if(blocks[b].type==='facility')return 'Ground Level';return floorNames[f];}
function fillBuildings(s){s.innerHTML=blocks.map((b,i)=>`<option value="${i}">${b.icon} ${b.name}</option>`).join('');}
function fillFloors(s,b){s.innerHTML=floorsFor(b).map((_,i)=>`<option value="${i}">${floorLabel(b,i)}</option>`).join('');}
function fillRooms(s,b,f){if(blocks[b]?.type==='temple'){s.innerHTML='';return;}s.innerHTML=roomsFor(b,f).map((r,i)=>`<option value="${i}">${r}</option>`).join('');}
function toggleRoomField(buildingSelect,roomField){const isTemple=blocks[+buildingSelect.value]?.type==='temple';roomField.hidden=isTemple;roomField.setAttribute('aria-hidden',String(isTemple));}
function placeName(b,f,r){if(blocks[b]?.type==='temple')return 'Campus Temple • Ground Floor';return `${blocks[b].name} • ${floorLabel(b,f)} • ${roomsFor(b,f)[r]||'Entrance'}`;}
function mapsSearchUrl(query){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;}
// Use Google Maps' current-device location as the origin. Do not force a fictional campus coordinate as origin.
function mapsDirectionsUrl(toBlock){const destination=encodeURIComponent(blocks[toBlock].query+', Idupulapaya, Andhra Pradesh, India');return `https://www.google.com/maps/dir/?api=1&destination=${destination}&travelmode=walking`;}
fillBuildings(currentBuilding);fillBuildings(destinationBuilding);fillFloors(currentFloor,0);fillFloors(destinationFloor,0);fillRooms(currentRoom,0,0);fillRooms(destinationRoom,0,0);toggleRoomField(currentBuilding,currentRoomField);toggleRoomField(destinationBuilding,destinationRoomField);
currentBuilding.addEventListener('change',()=>{fillFloors(currentFloor,+currentBuilding.value);fillRooms(currentRoom,+currentBuilding.value,+currentFloor.value);toggleRoomField(currentBuilding,currentRoomField);});
destinationBuilding.addEventListener('change',()=>{fillFloors(destinationFloor,+destinationBuilding.value);fillRooms(destinationRoom,+destinationBuilding.value,+destinationFloor.value);toggleRoomField(destinationBuilding,destinationRoomField);});
currentFloor.addEventListener('change',()=>fillRooms(currentRoom,+currentBuilding.value,+currentFloor.value));
destinationFloor.addEventListener('change',()=>fillRooms(destinationRoom,+destinationBuilding.value,+destinationFloor.value));
blocks.forEach(b=>{const d=document.createElement('div');d.className='place';let description;if(b.type==='hostel')description='3 floors • residential rooms • warden/common/study spaces • no labs';else if(b.type==='sports')description='Student Activity Centre • gym • tennis • basketball • badminton • indoor games';else if(b.type==='facility')description='Essential campus support facility • modeled at ground level';else if(b.type==='temple')description='Temple • ground floor • destination only';else if(b.type==='department')description=`Separate department block • ${b.department} • classrooms • labs • faculty/research spaces`;else description=`Academic block • smaller departments: ${b.smallDepartments.join(', ')}`;d.innerHTML=`<strong>${b.icon} ${b.name}</strong><span>${description}</span><div class="place-actions"><button class="place-destination" type="button">Set as destination →</button><button class="place-map" type="button">Open in Google Maps ↗</button></div>`;
  d.querySelector('.place-destination').addEventListener('click',()=>{
    const idx=blocks.indexOf(b);
    destinationBuilding.value=String(idx);
    fillFloors(destinationFloor,idx);
    destinationFloor.value='0';
    fillRooms(destinationRoom,idx,0);
    document.getElementById('navigate').scrollIntoView({behavior:'smooth',block:'center'});
    message.textContent=`${b.name} selected as your destination.`;
  });
  d.querySelector('.place-map').addEventListener('click',()=>window.open(mapsSearchUrl(b.query),'_blank','noopener,noreferrer'));
  locations.appendChild(d);});

const essentialCopy={
  'Campus Hospital':['🏥','Campus healthcare facility','Hospital & medical support'],
  'SBI Bank — Idupulapaya':['🏦','State Bank of India branch','AP IIIT Campus • Idupulapaya-Kadapa'],
  'SBI ATM — IIIT Campus':['🏧','State Bank of India ATM','AP IIIT Campus • Idupulapaya']
};
blocks.filter(b=>essentialCopy[b.name]).forEach(b=>{const d=document.createElement('div');d.className='facility';const c=essentialCopy[b.name];d.innerHTML=`<div class="facility-icon">${c[0]}</div><strong>${b.name}</strong><span>${c[1]}</span><span>${c[2]}</span><div class="facility-actions"><button class="facility-action" type="button">Set as destination →</button><button class="facility-map-action" type="button">Open in Google Maps ↗</button></div>`;d.querySelector('.facility-action').addEventListener('click',()=>{const idx=blocks.indexOf(b);destinationBuilding.value=String(idx);fillFloors(destinationFloor,idx);destinationFloor.value='0';fillRooms(destinationRoom,idx,0);document.getElementById('navigate').scrollIntoView({behavior:'smooth',block:'center'});message.textContent=`${b.name} selected as your destination.`;});
  d.querySelector('.facility-map-action').addEventListener('click',()=>window.open(mapsSearchUrl(b.query),'_blank','noopener,noreferrer'));
  essentialLocations.appendChild(d);
});
document.getElementById('templeDestination')?.addEventListener('click',()=>{const idx=blocks.findIndex(b=>b.name==='Campus Temple');destinationBuilding.value=String(idx);fillFloors(destinationFloor,idx);destinationFloor.value='0';fillRooms(destinationRoom,idx,0);toggleRoomField(destinationBuilding,destinationRoomField);document.getElementById('navigate').scrollIntoView({behavior:'smooth',block:'center'});message.textContent='Campus Temple selected as your destination.';});
document.getElementById('templeMap')?.addEventListener('click',()=>{const temple=blocks.find(b=>b.name==='Campus Temple');window.open(mapsSearchUrl(temple.query),'_blank','noopener,noreferrer');});
function nodeRoom(i){return `r${i}`;}function nodeCorridor(i){return `c${i}`;}
function buildGraph(count){const g={};for(let i=0;i<count;i++){const r=nodeRoom(i),c=nodeCorridor(i%5);g[r]??=[];g[c]??=[];g[r].push({to:c,cost:1});g[c].push({to:r,cost:1});}for(let i=0;i<4;i++){g[nodeCorridor(i)].push({to:nodeCorridor(i+1),cost:1});g[nodeCorridor(i+1)].push({to:nodeCorridor(i),cost:1});}return g;}
function aStar(g,start,goal){const open=[start],came={},cost={[start]:0},score={[start]:1};while(open.length){open.sort((a,b)=>score[a]-score[b]);const cur=open.shift();if(cur===goal){const path=[cur];while(came[path[0]])path.unshift(came[path[0]]);return path;}for(const e of g[cur]||[]){const n=(cost[cur]??Infinity)+e.cost;if(n<(cost[e.to]??Infinity)){came[e.to]=cur;cost[e.to]=n;score[e.to]=n+(e.to===goal?0:1);if(!open.includes(e.to))open.push(e.to);}}}return [];}
function center(i,count){const row=i%5,side=i<Math.ceil(count/2)?'left':'right';return side==='left'?{x:17,y:12+row*17}:{x:83,y:12+row*17};}
function routeSvg(c,d,b,f){if(c<0||d<0||c===d)return '';const count=roomsFor(b,f).length,path=aStar(buildGraph(count),nodeRoom(c),nodeRoom(d));if(!path.length)return '';const pts=path.map(n=>n[0]==='r'?center(Number(n.slice(1)),count):{x:50,y:12+Number(n.slice(1))*17});const line=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');return `<svg class="route-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Calculated indoor route"><defs><marker id="arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z" fill="#2563eb"/></marker></defs><path class="route-shadow" d="${line}"/><path class="route-line" d="${line}" marker-end="url(#arrow)"/><circle class="route-start" cx="${pts[0].x}" cy="${pts[0].y}" r="2.2"/><circle class="route-end" cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="2.5"/></svg>`;}
function renderFloorMap(b,f,c,d,show=true){if(blocks[b]?.type==='temple'){floorPreview.innerHTML=`<div class="floor-title">Campus Temple — Ground Floor <span class="prototype-label">(prototype)</span></div><div class="map-legend"><span class="legend-item"><i class="legend-dot destination"></i> Destination</span></div><div class="floor-map-shell"><div class="floor-map temple-map"><div class="floor-map-label">Ground floor • Campus Temple</div><div class="temple-only">🛕<strong>CAMPUS TEMPLE</strong><span>Ground floor • Destination only</span></div><div class="entrance">🚪 TEMPLE ENTRANCE</div></div></div><div class="map-note">Campus Temple is modeled as a single ground-floor destination.</div>`;return;}const rooms=roomsFor(b,f),markup=rooms.map((r,i)=>`<div class="room ${i===c?'current':''} ${i===d?'destination':''}" style="grid-column:${i<Math.ceil(rooms.length/2)?1:3};grid-row:${i%5+1}"><span>${r}</span></div>`).join(''),route=show?routeSvg(c,d,b,f):'';floorPreview.innerHTML=`<div class="floor-title">${blocks[b].name} — ${floorLabel(b,f)} <span class="prototype-label">(prototype)</span></div><div class="map-legend"><span class="legend-item"><i class="legend-dot current"></i> Current</span><span class="legend-item"><i class="legend-dot destination"></i> Destination</span><span class="legend-item"><i class="legend-dot route"></i> Calculated route</span><span class="legend-item"><i class="legend-dot stairs"></i> Stairs / elevator</span></div><div class="floor-map-shell"><div class="floor-map"><div class="floor-map-label">Conceptual floor plan • ${blocks[b].name}</div><div class="floor-plan">${markup}<div class="corridor">↕ MAIN CORRIDOR<br>↕</div>${route}</div><div class="entrance">🚪 MAIN ENTRANCE</div><div class="stairs">🪜 STAIRS + ELEVATOR</div></div></div><div class="map-note">Simulated navigation graph for the prototype. Hostel blocks contain residential rooms and common facilities only — no lab rooms. Academic blocks contain the smaller departments; CSE/ECE/EEE/Civil/MME/ME are modeled as separate department blocks. Replace prototype geometry with official floor data when available.</div>`;}
function addStep(text){const n=steps.children.length+1,e=document.createElement('div');e.className='step';e.innerHTML=`<div class="step-number">${n}</div><div>${text}</div>`;steps.appendChild(e);}
function setMapsButtons(toBlock){googleMaps.hidden=false;googleMaps.textContent='🌍 Open Outdoor Route in Google Maps';googleMaps.onclick=()=>window.open(mapsDirectionsUrl(toBlock),'_blank','noopener,noreferrer');document.getElementById('mapsSearchFallback')?.remove();const searchButton=document.createElement('button');searchButton.id='mapsSearchFallback';searchButton.className='secondary-button';searchButton.textContent='📍 Search Destination in Google Maps';searchButton.onclick=()=>window.open(mapsSearchUrl(blocks[toBlock].query),'_blank','noopener,noreferrer');googleMaps.parentElement.appendChild(searchButton);}
document.getElementById('navigate').addEventListener('click',()=>{const cb=+currentBuilding.value,cf=+currentFloor.value,cr=+currentRoom.value,db=+destinationBuilding.value,df=+destinationFloor.value,dr=+destinationRoom.value;routeResult.hidden=false;steps.innerHTML='';floorPreview.innerHTML='';googleMaps.hidden=true;document.getElementById('mapsSearchFallback')?.remove();message.textContent='';if(cb===db&&cf===df&&cr===dr){routeSummary.textContent=`You are already at ${placeName(db,df,dr)}.`;addStep('No route is needed — your current location and destination are the same.');renderFloorMap(db,df,cr,dr,false);return;}routeSummary.textContent=`${placeName(cb,cf,cr)} → ${placeName(db,df,dr)}`;addStep(`Start at ${placeName(cb,cf,cr)}.`);if(blocks[db]?.type==='temple'){addStep('Follow the route to Campus Temple.');addStep('Arrive at the ground-floor temple entrance.');renderFloorMap(db,df,-1,-1,false);setMapsButtons(db);return;}if(cb===db&&cf===df){addStep('Follow the calculated blue route through the corridor.');addStep(`Arrive at ${roomsFor(db,df)[dr]} 🎯.`);renderFloorMap(db,df,cr,dr,true);return;}if(cb===db){addStep('Follow the indoor route to the nearest stairs/elevator.');addStep(`Take the stairs/elevator from ${floorLabel(cb,cf)} to ${floorLabel(db,df)}.`);addStep(`Follow the corridor on ${floorLabel(db,df)} to ${roomsFor(db,df)[dr]}.`);renderFloorMap(db,df,-1,dr,false);return;}addStep(`Follow the indoor route to the ${blocks[cb].name} entrance/exit.`);addStep(`For the outdoor section, Google Maps will use your phone's current location to route to ${blocks[db].name}.`);addStep(blocks[db].name==='Campus Temple'?`At Campus Temple, arrive at the ground-floor temple entrance.`:`At ${blocks[db].name}, go to ${floorLabel(db,df)} and follow the indoor route to ${roomsFor(db,df)[dr]}.`);setMapsButtons(db);renderFloorMap(db,df,-1,dr,false);});