const blocks=[
  {name:'AB-1',icon:'🏢',query:'Academic Block 1, IIIT RGUKT RK Valley',type:'academic'},
  {name:'AB-2',icon:'🏢',query:'Academic Block 2, IIIT RGUKT RK Valley',type:'academic'},
  {name:'BH-1',icon:'🏠',query:'Boys Hostel 1, IIIT RGUKT RK Valley',type:'hostel'},
  {name:'BH-2',icon:'🏠',query:'Boys Hostel 2, IIIT RGUKT RK Valley',type:'hostel'},
  {name:'GH-1',icon:'🏠',query:'Girls Hostel 1, IIIT RGUKT RK Valley',type:'hostel'}
];
const academicFloors={0:['101','102','103','104','105 — Lab','106 — Lab','107','108','109','110 — Office'],1:['201','202','203','204','205 — Lab','206 — Lab','207','208','209','210 — Faculty Room'],2:['301','302','303','304','305 — Seminar','306 — Project Lab','307','308','309','310 — Common Room']};
const hostelFloors={0:['101','102','103','104','105','106','107','108','109','110 — Warden Office'],1:['201','202','203','204','205','206','207','208','209','210 — Common Room'],2:['301','302','303','304','305','306','307','308','309','310 — Study Room']};
const floorNames=['Ground Floor','First Floor','Second Floor'];
const currentBuilding=document.getElementById('currentBuilding'),currentFloor=document.getElementById('currentFloor'),currentRoom=document.getElementById('currentRoom');
const destinationBuilding=document.getElementById('destinationBuilding'),destinationFloor=document.getElementById('destinationFloor'),destinationRoom=document.getElementById('destinationRoom');
const message=document.getElementById('message'),routeResult=document.getElementById('routeResult'),routeSummary=document.getElementById('routeSummary'),steps=document.getElementById('steps'),floorPreview=document.getElementById('floorPreview'),googleMaps=document.getElementById('googleMaps'),locations=document.getElementById('locations');
function facilities(b,f){return blocks[b].type==='hostel'?hostelFloors[f]:academicFloors[f];}
function fillBuildings(s){s.innerHTML=blocks.map((b,i)=>`<option value="${i}">${b.icon} ${b.name}</option>`).join('');}
function fillFloors(s){s.innerHTML=floorNames.map((f,i)=>`<option value="${i}">${f}</option>`).join('');}
function fillRooms(s,b,f){s.innerHTML=facilities(b,f).map((r,i)=>`<option value="${i}">${r}</option>`).join('');}
function placeName(b,f,r){return `${blocks[b].name} • ${floorNames[f]} • ${facilities(b,f)[r]}`;}
function mapsUrl(a,b){return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(blocks[a].query)}&destination=${encodeURIComponent(blocks[b].query)}&travelmode=walking`;}
fillBuildings(currentBuilding);fillBuildings(destinationBuilding);fillFloors(currentFloor);fillFloors(destinationFloor);fillRooms(currentRoom,0,0);fillRooms(destinationRoom,0,0);
currentBuilding.addEventListener('change',()=>fillRooms(currentRoom,Number(currentBuilding.value),Number(currentFloor.value)));
destinationBuilding.addEventListener('change',()=>fillRooms(destinationRoom,Number(destinationBuilding.value),Number(destinationFloor.value)));
currentFloor.addEventListener('change',()=>fillRooms(currentRoom,Number(currentBuilding.value),Number(currentFloor.value)));
destinationFloor.addEventListener('change',()=>fillRooms(destinationRoom,Number(destinationBuilding.value),Number(destinationFloor.value)));
blocks.forEach(b=>{const d=document.createElement('div');d.className='place';d.innerHTML=`<strong>${b.icon} ${b.name}</strong><span>3 floors • 30 prototype spaces • ${b.type==='hostel'?'residential rooms and common facilities':'classrooms, labs and academic facilities'}</span>`;locations.appendChild(d);});
// A* pathfinding over the conceptual corridor graph.
function nodeRoom(i){return `r${i}`;} function nodeCorridor(i){return `c${i}`;}
function buildGraph(count){const g={};for(let i=0;i<count;i++){const r=nodeRoom(i),c=nodeCorridor(i%5);g[r]??=[];g[c]??=[];g[r].push({to:c,cost:1});g[c].push({to:r,cost:1});}for(let i=0;i<4;i++){g[nodeCorridor(i)].push({to:nodeCorridor(i+1),cost:1});g[nodeCorridor(i+1)].push({to:nodeCorridor(i),cost:1});}return g;}
function aStar(g,start,goal){const open=[start],came={},cost={[start]:0},score={[start]:1};while(open.length){open.sort((a,b)=>score[a]-score[b]);const cur=open.shift();if(cur===goal){const path=[cur];while(came[path[0]])path.unshift(came[path[0]]);return path;}for(const e of g[cur]||[]){const n=(cost[cur]??Infinity)+e.cost;if(n<(cost[e.to]??Infinity)){came[e.to]=cur;cost[e.to]=n;score[e.to]=n+(e.to===goal?0:1);if(!open.includes(e.to))open.push(e.to);}}}return [];}
function roomClass(i,c,d){const x=['room'];if(i===c)x.push('current');if(i===d)x.push('destination');return x.join(' ');}
function center(i){const row=i%5,side=i<5?'left':'right';return side==='left'?{x:17,y:12+row*19}:{x:83,y:12+row*19};}
function routeSvg(c,d,b,f){if(c<0||d<0||c===d)return '';const path=aStar(buildGraph(facilities(b,f).length),nodeRoom(c),nodeRoom(d));if(!path.length)return '';const pts=path.map(n=>n[0]==='r'?center(Number(n.slice(1))):{x:50,y:12+Number(n.slice(1))*19});const line=pts.map((p,i)=>`${i?'L':'M'} ${p.x} ${p.y}`).join(' ');return `<svg class="route-overlay" viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Calculated indoor route"><defs><marker id="arrow" markerWidth="5" markerHeight="5" refX="4" refY="2.5" orient="auto"><path d="M0,0 L5,2.5 L0,5 Z" fill="#2563eb"/></marker></defs><path class="route-shadow" d="${line}"/><path class="route-line" d="${line}" marker-end="url(#arrow)"/><circle class="route-start" cx="${pts[0].x}" cy="${pts[0].y}" r="2.2"/><circle class="route-end" cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="2.5"/></svg>`;}
function renderFloorMap(b,f,c,d,show=true){const rooms=facilities(b,f);const markup=rooms.map((r,i)=>`<div class="${roomClass(i,c,d)}" style="grid-column:${i<5?1:3};grid-row:${i%5+1}"><span>${r}</span></div>`).join('');const route=show?routeSvg(c,d,b,f):'';floorPreview.innerHTML=`<div class="floor-title">${blocks[b].name} — ${floorNames[f]} <span class="prototype-label">(prototype)</span></div><div class="map-legend"><span class="legend-item"><i class="legend-dot current"></i> Current</span><span class="legend-item"><i class="legend-dot destination"></i> Destination</span><span class="legend-item"><i class="legend-dot route"></i> Calculated route</span><span class="legend-item"><i class="legend-dot stairs"></i> Stairs / elevator</span></div><div class="floor-map-shell"><div class="floor-map"><div class="floor-map-label">Conceptual floor plan • ${blocks[b].name}</div><div class="floor-plan">${markup}<div class="corridor">↕ MAIN CORRIDOR<br>↕</div>${route}</div><div class="entrance">🚪 MAIN ENTRANCE</div><div class="stairs">🪜 STAIRS + ELEVATOR</div></div></div><div class="map-note">Simulated navigation graph for the prototype. Hostel blocks contain residential rooms and common facilities only — no lab rooms. Replace the conceptual graph with the official building plan when available.</div>`;}
function addStep(text){const n=steps.children.length+1,e=document.createElement('div');e.className='step';e.innerHTML=`<div class="step-number">${n}</div><div>${text}</div>`;steps.appendChild(e);}
document.getElementById('navigate').addEventListener('click',()=>{const cb=+currentBuilding.value,cf=+currentFloor.value,cr=+currentRoom.value,db=+destinationBuilding.value,df=+destinationFloor.value,dr=+destinationRoom.value;routeResult.hidden=false;steps.innerHTML='';floorPreview.innerHTML='';googleMaps.hidden=true;message.textContent='';if(cb===db&&cf===df&&cr===dr){routeSummary.textContent=`You are already at ${placeName(db,df,dr)}.`;addStep('No route is needed — your current location and destination are the same.');renderFloorMap(db,df,cr,dr,false);return;}routeSummary.textContent=`${placeName(cb,cf,cr)} → ${placeName(db,df,dr)}`;addStep(`Start at ${placeName(cb,cf,cr)}.`);if(cb===db&&cf===df){addStep('Follow the calculated blue A* route through the corridor.');addStep(`Arrive at ${facilities(db,df)[dr]} 🎯.`);renderFloorMap(db,df,cr,dr,true);return;}if(cb===db){addStep('Follow the calculated indoor route to the stairs/elevator.');addStep(`Take the stairs/elevator from ${floorNames[cf]} to ${floorNames[df]}.`);addStep(`Follow the corridor on ${floorNames[df]} to ${facilities(db,df)[dr]}.`);renderFloorMap(db,df,-1,dr,false);return;}addStep('Follow the indoor route to the building entrance/exit.');addStep(`Continue outdoors from ${blocks[cb].name} to ${blocks[db].name} using Google Maps.`);addStep(`At ${blocks[db].name}, go to ${floorNames[df]} and follow the indoor route to ${facilities(db,df)[dr]}.`);googleMaps.hidden=false;googleMaps.onclick=()=>window.open(mapsUrl(cb,db),'_blank','noopener,noreferrer');renderFloorMap(db,df,-1,dr,false);});